name: mptest
favicon: null
layout_spectrum: 0.7050800682045519
typography_spectrum: 0.7789
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000f00'
    - '#49854a'
    - '#f9ffd9'
    - '#a1d670'
    - '#b7888e'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
